Add support for importing images from new filemanager from network storage
IMGIITRoorkee/omniport-service-maintainer-site pull request #4
Opened 2021-01-06 11:27 UTC by gauransh7

Add support for importing images from new filemanager from network storage.

2021-01-06 15:35 UTC, algomaster99 requested changes
You should delete the `personal_to_media` view if that is not needed anymore.

Can you explain why this change in the context of new filemanager is necessary though?

2021-01-06 21:31 UTC, gauransh7 commented
> You should delete the `personal_to_media` view if that is not needed anymore.
> 
> Can you explain why this change in the context of new filemanager is necessary though?

Yes, we don't need it for now, I will delete it.

In the previous filemanager version we were storing files in the personal_files folder, Now in the new version we store the files in network_storage folder.
So while rendering images in the editor of add_project_details on frontend we copy images from network_storage to media instead of personal_files to media.

2021-01-07 10:08 UTC, algomaster99 approved these changes

2021-01-07 10:08 UTC, merged

2021-01-07 10:11 UTC, algomaster99 commented
@gagansh7171 @pradumangoyal Is the new file manager is on production? If yes, I will pull these changes there.